version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@0.0.3
jobs:
  run-bridgecrew:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: "."
          soft-fail: true
workflows:
  bridgecrew-scan:
    jobs:
      - run-bridgecrew
