version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@0.0.4
jobs:
  run-bridgecrew:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/install
      - bridgecrew/scan:
          directory: "./terraform"
          soft-fail: true
          output: "json"
workflows:
  bridgecrew-scan:
    jobs:
      - run-bridgecrew
